# Competition: AI Agents Intensive Vibe Coding - Kaggle 2026
"""
agents/reviewer_agent.py
---------------------------
PURPOSE:
    The ReviewerAgent is a reflection and quality-control agent in the sales pipeline.
    It receives an email draft generated by the OutreachDrafter and evaluates it
    across 5 key dimensions: Personalization, Clarity, Tone, Call to Action, and Subject Line.

    If the draft score is below a threshold (35/50), it performs self-correction
    (reflection) by rewriting the email to improve it.

    It returns a structured review containing the original score, improved score,
    and the final email (either original or improved).

THE REFLECTION PATTERN:
    Reflection is a design pattern in agentic systems where an agent evaluates its
    own or another agent's output and uses that critique to refine the work.
    In multi-agent architectures, this acts as a quality gate.
    
    Why it improves output quality:
    1. Error Detection & Self-Correction: Large Language Models (LLMs) often make minor
       mistakes or generate generic prose on the first pass (zero-shot). By prompting
       the model to explicitly criticize and grade the output first, we activate its
       reasoning capabilities to detect weaknesses before returning the response.
    2. Decoupled Concerns: The generator agent (OutreachDrafter) focuses on styling and
       personalization, while the reviewer agent (ReviewerAgent) focuses on validation
       against specific criteria. This keeps agent prompts simpler and less prone to
       instruction drift.
    3. Iterative Refinement: Feedback loops allow the system to self-correct
       hallucinations or quality issues, leading to much more polished and higher-converting
       end-results.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import sys
import time
from pathlib import Path
from typing import TypedDict

# ─── Path fix ─────────────────────────────────────────────────────────────────
_PROJECT_ROOT = str(Path(__file__).resolve().parent.parent)
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from dotenv import load_dotenv
from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types as genai_types

# Load .env so this module works when imported or run directly.
load_dotenv()

# Verify that the API Key is loaded from environment variables and not hardcoded
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
if not GOOGLE_API_KEY:
    raise ValueError("SECURITY ERROR: GOOGLE_API_KEY environment variable is not set. API keys must never be hardcoded.")

def log_action(agent_name: str, action: str, details: str = "") -> None:
    """Log an agent action to agent_log.txt with a UTC ISO-8601 timestamp."""
    from datetime import datetime, timezone
    timestamp = datetime.now(timezone.utc).isoformat()
    log_line = f"[{timestamp}] {agent_name} | {action} | {details}\n"
    try:
        with open("agent_log.txt", "a", encoding="utf-8") as f:
            f.write(log_line)
    except Exception as e:
        sys.stderr.write(f"Logging error: {e}\n")


# =============================================================================
# SECTION 1 — OUTPUT SCHEMA
# =============================================================================

class ScoreBreakdown(TypedDict):
    personalization: int
    clarity: int
    tone: int
    call_to_action: int
    subject_line: int
    total: int

class FinalEmail(TypedDict):
    subject: str
    body: str

class ReviewResult(TypedDict):
    original_score: ScoreBreakdown
    is_rewritten: bool
    improved_score: ScoreBreakdown
    final_email: FinalEmail


# =============================================================================
# SECTION 2 — PROMPTING CONSTANTS
# =============================================================================

_REVIEWER_INSTRUCTION_TEMPLATE = """\
You are an expert copywriter, B2B sales coach, and quality assurance agent.
Your job is to review a draft cold email sent to a prospect and score it across 5 dimensions on a scale of 1-10:

1. Personalization: Does it reference the prospect's company name and their specific pain points in a tailored, natural way? (1-10)
2. Clarity: Is the value proposition immediately clear and easy to understand without jargon? (1-10)
3. Tone: Is the email professional, helpful, and consultative, avoiding spammy, salesy, or hype-filled language? (1-10)
4. Call to Action (CTA): Is the call to action specific, low-friction, and easy to say yes to? (1-10)
5. Subject Line: Is the subject line compelling, relevant, and strictly under 60 characters? (1-10)

Evaluation Rubric:
- Score 1-10 for each dimension.
- Sum the scores to compute the Total Score (out of 50).
- If the Total Score is LESS than 35, you MUST rewrite the email (both subject and body) to address all criteria, ensuring it reaches a high quality score (40+).
- If the Total Score is 35 or higher, do NOT rewrite the email; return the original subject and body.

Company Name: {company_name}
Specific Pain Points: {pain_points}

Draft Email to Review:
Subject: {original_subject}
Body:
{original_body}

Output your response EXACTLY as a JSON block wrapped in ```json and ```. Do not include any other text outside the JSON block.

Required JSON Structure:
```json
{{
  "original_score": {{
    "personalization": <int 1-10>,
    "clarity": <int 1-10>,
    "tone": <int 1-10>,
    "call_to_action": <int 1-10>,
    "subject_line": <int 1-10>,
    "total": <sum of dimensions, int 5-50>
  }},
  "is_rewritten": <true|false>,
  "improved_score": {{
    "personalization": <int 1-10>,
    "clarity": <int 1-10>,
    "tone": <int 1-10>,
    "call_to_action": <int 1-10>,
    "subject_line": <int 1-10>,
    "total": <sum of dimensions, int 5-50>
  }},
  "final_email": {{
    "subject": "<final or rewritten subject line>",
    "body": "<final or rewritten email body text>"
  }}
}}
```
"""


# =============================================================================
# SECTION 3 — AGENT CREATION
# =============================================================================

def _build_standalone_agent(
    company_name: str,
    pain_points: list[str],
    original_subject: str,
    original_body: str,
    model: str,
) -> Agent:
    instruction = _REVIEWER_INSTRUCTION_TEMPLATE.format(
        company_name=company_name,
        pain_points=", ".join(pain_points) if pain_points else "None",
        original_subject=original_subject,
        original_body=original_body,
    )
    return Agent(
        name="reviewer_agent_standalone",
        model=model,
        description="Reviewer and Reflection agent that scores and improves cold email drafts.",
        instruction=instruction,
    )


# =============================================================================
# SECTION 4 — JSON EXTRACTION HELPER
# =============================================================================

def _extract_review_json(text: str) -> dict:
    pattern = r"```json\s*([\s\S]*?)\s*```"
    match = re.search(pattern, text, re.DOTALL)
    if not match:
        return {}
    try:
        return json.loads(match.group(1))
    except json.JSONDecodeError:
        return {}


# =============================================================================
# SECTION 5 — PUBLIC API
# =============================================================================

async def _run_review_async(
    company_name: str,
    email_subject: str,
    email_body: str,
    pain_points: list[str],
    model_name: str | None = None,
) -> ReviewResult:
    """Internal async implementation of review_email() with fallback chain."""
    log_action("ReviewerAgent", "AGENT_RUN_START", f"company={company_name}")
    app_name = "reviewer_agent"

    initial_message = genai_types.Content(
        role="user",
        parts=[genai_types.Part(
            text=f"Review the draft email for {company_name} and output the JSON scoring structure."
        )],
    )

    models = [model_name] if model_name else ["gemini-2.0-flash", "gemini-2.0-flash-lite", "gemini-1.5-flash-latest"]
    # NOTE: gemini-1.5-flash-latest is the last model fallback before raising
    # the error and returning the hard fallback ReviewResult.
    raw_response = ""
    last_error: Exception | None = None
    success = False

    for current_model in models:
        if not current_model:
            continue
        print(f"🤖 Using model: {current_model}")
        log_action("ReviewerAgent", "MODEL_SELECTION", f"model={current_model}")

        session_service = InMemorySessionService()
        session = await session_service.create_session(
            app_name=app_name,
            user_id="standalone_user",
            state={},
        )

        agent = _build_standalone_agent(
            company_name=company_name,
            pain_points=pain_points,
            original_subject=email_subject,
            original_body=email_body,
            model=current_model,
        )

        runner = Runner(
            agent=agent,
            app_name=app_name,
            session_service=session_service,
        )

        MAX_RETRIES = 3
        BACKOFF_BASE = 2

        for attempt in range(1, MAX_RETRIES + 1):
            try:
                async for event in runner.run_async(
                    user_id="standalone_user",
                    session_id=session.id,
                    new_message=initial_message,
                ):
                    if event.is_final_response():
                        content = event.content
                        if content and content.parts:
                            raw_response = "".join(
                                p.text for p in content.parts
                                if hasattr(p, "text") and p.text
                            )
                success = True
                break
            except Exception as exc:
                last_error = exc
                err = str(exc)
                is_transient = any(k in err for k in ("503", "429", "UNAVAILABLE", "RESOURCE_EXHAUSTED"))
                if is_transient and attempt < MAX_RETRIES:
                    wait = BACKOFF_BASE ** attempt
                    print(f"  [ReviewerAgent] Attempt {attempt}/{MAX_RETRIES} failed with model {current_model} ({err[:80]}). Retrying in {wait}s…")
                    await asyncio.sleep(wait)
                    session = await session_service.create_session(
                        app_name=app_name,
                        user_id="standalone_user",
                        state={},
                    )
                else:
                    print(f"  [ReviewerAgent] Model {current_model} failed/exhausted ({err[:80]}). Trying next model in fallback chain...")
                    break
        if success:
            break
    else:
        if last_error:
            log_action("ReviewerAgent", "AGENT_RUN_ERROR", f"company={company_name}, error={str(last_error)[:100]}")
            raise last_error

    parsed = _extract_review_json(raw_response)
    if parsed and "original_score" in parsed and "final_email" in parsed:
        log_action(
            "ReviewerAgent",
            "AGENT_RUN_SUCCESS",
            f"company={company_name}, orig_score={parsed['original_score'].get('total', 0)}, is_rewritten={parsed.get('is_rewritten', False)}",
        )
        return ReviewResult(
            original_score=parsed["original_score"],
            is_rewritten=parsed.get("is_rewritten", False),
            improved_score=parsed.get("improved_score", parsed["original_score"]),
            final_email=parsed["final_email"],
        )

    # Hard fallback in case parsing fails
    fallback_breakdown = ScoreBreakdown(
        personalization=5, clarity=5, tone=5, call_to_action=5, subject_line=5, total=25
    )
    log_action("ReviewerAgent", "AGENT_RUN_FALLBACK", f"company={company_name}, parsing failed")
    return ReviewResult(
        original_score=fallback_breakdown,
        is_rewritten=True,
        improved_score=fallback_breakdown,
        final_email=FinalEmail(subject=email_subject, body=email_body),
    )


def review_email(
    company_name: str,
    email_subject: str,
    email_body: str,
    pain_points: list[str],
    model_name: str | None = None,
) -> ReviewResult:
    """Public synchronous API for evaluating and reflecting on email drafts."""
    try:
        return asyncio.run(
            _run_review_async(
                company_name=company_name,
                email_subject=email_subject,
                email_body=email_body,
                pain_points=pain_points,
                model_name=model_name,
            )
        )
    except Exception as e:
        # Guarantee a return structure on exception
        fallback_breakdown = ScoreBreakdown(
            personalization=5, clarity=5, tone=5, call_to_action=5, subject_line=5, total=25
        )
        return ReviewResult(
            original_score=fallback_breakdown,
            is_rewritten=False,
            improved_score=fallback_breakdown,
            final_email=FinalEmail(subject=email_subject, body=email_body),
        )
